#local
version: "3.9"

services:
  # ===================== EUREKA SERVER =====================
  eureka-server:
    image: upiq-eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - upiq-network

  # ===================== USER AUTH SERVICE =====================
  user-auth-db:
    image: upiq-user-auth-db:16
    container_name: user-auth-db
    environment:
      POSTGRES_DB: userauthdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - upiq-network

  user-auth-service:
    image: upiq-user-auth-service:latest
    container_name: user-auth-service
    environment:
      DB_HOST: user-auth-db
      DB_USER: postgres
      DB_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - user-auth-db
    ports:
      - "8081:8081"
    networks:
      - upiq-network

  # ===================== PDF PARSER SERVICE =====================
  pdf-parser-service:
    image: upiq-pdf-parser-service:latest
    container_name: pdf-parser-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    ports:
      - "8082:8082"
    networks:
      - upiq-network

  # ===================== TRANSACTION SERVICE =====================
  transaction-db:
    image: upiq-transaction-db:16
    container_name: transaction-db
    environment:
      POSTGRES_DB: Transactiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    networks:
      - upiq-network

  transaction-service:
    image: upiq-transaction-service:latest
    container_name: transaction-service
    environment:
      DB_HOST: transaction-db
      DB_USER: postgres
      DB_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - transaction-db
    ports:
      - "8083:8083"
    networks:
      - upiq-network

  # ===================== CATEGORY SERVICE =====================
  category-db:
    image: upiq-category-db:16
    container_name: category-db
    environment:
      POSTGRES_DB: Categorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    networks:
      - upiq-network

  category-service:
    image: upiq-category-service:latest
    container_name: category-service
    environment:
      DB_HOST: category-db
      DB_USER: postgres
      DB_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - category-db
    ports:
      - "8084:8084"
    networks:
      - upiq-network

  # ===================== API GATEWAY =====================
  api-gateway:
    image: upiq-api-gateway:latest
    container_name: api-gateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - user-auth-service
      - pdf-parser-service
      - transaction-service
      - category-service
    ports:
      - "8080:8080"
    networks:
      - upiq-network

# ===================== NETWORK =====================
networks:
  upiq-network:
    driver: bridge
