server:
  port: 8080

spring:
  application:
    name: UPIQ-APIGateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false

      routes:
        # Auth Service
        - id: user-auth-service
          uri: lb://UPIQ-USER-AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/auth/**

        # PDF Parser Service
        - id: pdf-parser-service
          uri: lb://UPIQ-PDFPARSER-SERVICE
          predicates:
            - Path=/api/pdf/**

        # Transaction Service
        - id: transaction-service
          uri: lb://UPIQ-TRANSACTION-SERVICE
          predicates:
            - Path=/api/transaction/**

        # Category Service
        - id: category-service
          uri: lb://UPIQ-CATEGORY-SERVICE
          predicates:
            - Path=/api/categories/**

  webflux:
    cors:
      allowed-origins:
        - "http://localhost:5173"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - Authorization
        - Content-Type
      allow-credentials: true

jwt:
  secret: OvZseP71KwAAWUuC6jdiKL3WiefJmXeVTqUQL5jlG7EyjiXmhUqIK38D5/LGyIVZpCWaSZQ9W6hnvCJtQzABog==
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: INFO
