#Global
version: "3.9"

services:
  # ================= POSTGRES DATABASES =================
  user-auth-db:
    image: yourxharsh19/upiq-user-auth-db:16
    container_name: user-auth-db
    environment:
      POSTGRES_DB: UserAuthdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  category-db:
    image: yourxharsh19/upiq-category-db:16
    container_name: category-db
    environment:
      POSTGRES_DB: Categorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"

  transaction-db:
    image: yourxharsh19/upiq-transaction-db:16
    container_name: transaction-db
    environment:
      POSTGRES_DB: Transactiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"

  # ================= SERVICES =================
  eureka-server:
    image: yourxharsh19/upiq-eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"

  user-auth-service:
    image: yourxharsh19/upiq-user-auth-service:latest
    container_name: user-auth-service
    ports:
      - "8081:8081"
    depends_on:
      - user-auth-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-auth-db:5432/UserAuthdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  category-service:
    image: yourxharsh19/upiq-category-service:latest
    container_name: category-service
    ports:
      - "8084:8084"
    depends_on:
      - category-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://category-db:5432/Categorydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  transaction-service:
    image: yourxharsh19/upiq-transaction-service:latest
    container_name: transaction-service
    ports:
      - "8083:8083"
    depends_on:
      - transaction-db
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://transaction-db:5432/Transactiondb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  pdf-parser-service:
    image: yourxharsh19/upiq-pdf-parser-service:latest
    container_name: pdf-parser-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  api-gateway:
    image: yourxharsh19/upiq-api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - user-auth-service
      - pdf-parser-service
      - transaction-service
      - category-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      JWT_SECRET: OvZseP71KwAAWUuC6jdiKL3WiefJmXeVTqUQL5jlG7EyjiXmhUqIK38D5/LGyIVZpCWaSZQ9W6hnvCJtQzABog==
      JWT_EXPIRATION: 3600000
      USER_AUTH_SERVICE_URL: http://user-auth-service
      PDF_PARSER_SERVICE_URL: http://pdf-parser-service
      TRANSACTION_SERVICE_URL: http://transaction-service
      CATEGORY_SERVICE_URL: http://category-service
